height = float(input("What is your height in meters?"))
weight = float(input("What is your weight in kilograms?"))
bmi = weight / (height ** 2)
if bmi < 18.5: print(f"Your BMI is {bmi} and you are underweight.")
elif bmi >= 18.5 and bmi < 25: print(f"Your BMI is {bmi} and you have a normal weight.")
elif bmi >= 25 and bmi < 30: print(f"Your BMI is {bmi} and you are overweight.")
else: print(f"Your BMI is {bmi} and you are obese.")
